export { default as Slide } from './components/Slide.svelte';
export { default as Code } from './components/Code.svelte';
export { default as Notes } from './components/Notes.svelte';
export { default as Deck } from './components/Deck.svelte';
export { default as Screenshot } from './components/Screenshot.svelte';
export { default as ResourceChart } from './components/ResourceChart.svelte';
export { default as SearchPipeline } from './components/SearchPipeline.svelte';
export { default as FeatureCard } from './components/FeatureCard.svelte';
export { default as PersonCard } from './components/PersonCard.svelte';
